// Package archive extracts bounded comic pages from ZIP and RAR archives.
package archive

import (
	"archive/zip"
	"bytes"
	"context"
	"errors"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nwaples/rardecode/v2"
	_ "golang.org/x/image/webp"
)

const (
	// MaxImagePixels bounds raster dimensions before full image decoding.
	MaxImagePixels = 64 << 20

	megabyte int64 = 1 << 20
	gigabyte int64 = 1 << 30

	// The dependency documents 256 KiB as the smallest usable RAR window.
	maxRARDictionaryBytes int64 = 64 << 30
)

// DefaultLimits are the protocol's bounded extraction defaults. A zero field
// in Limits uses the corresponding default.
var DefaultLimits = Limits{
	MaxEntries:         2048,
	MaxPageBytes:       32 * megabyte,
	MaxTotalBytes:      1 * gigabyte,
	MaxArchiveBytes:    512 * megabyte,
	MaxDictionaryBytes: 64 * megabyte,
}

// Limits bounds both archive input and decoded entry data. MaxTotalBytes is
// charged for bytes read from every regular entry, including entries that are
// later skipped because they are not images.
//
// MaxArchiveBytes bounds the compressed archive file itself. It is an
// additional field to the original API proposal so the protocol's archive
// input limit is enforced by this package as well.
type Limits struct {
	MaxEntries         int   `json:"max_entries,omitempty"`
	MaxPageBytes       int64 `json:"max_page_bytes,omitempty"`
	MaxTotalBytes      int64 `json:"max_total_bytes,omitempty"`
	MaxArchiveBytes    int64 `json:"max_archive_bytes,omitempty"`
	MaxDictionaryBytes int64 `json:"max_dictionary_bytes,omitempty"`
}

// Page describes one validated image written to the extraction directory.
// File is an opaque sequential filename generated by this package.
type Page struct {
	Name      string `json:"name"`
	File      string `json:"file"`
	Size      int64  `json:"size"`
	MediaType string `json:"media_type"`
}

var (
	// ErrInvalidLimits reports a zero or negative limit after defaulting.
	ErrInvalidLimits = errors.New("archive: invalid limits")
	// ErrInvalidInput reports a missing, non-regular, or symlinked archive.
	ErrInvalidInput = errors.New("archive: invalid input")
	// ErrInvalidOutput reports an unusable extraction directory.
	ErrInvalidOutput = errors.New("archive: invalid output directory")
	// ErrUnsupportedArchive reports a format other than ZIP, RAR4, or RAR5.
	ErrUnsupportedArchive = errors.New("archive: unsupported archive")
	// ErrCorruptArchive reports malformed archive structure or checksums.
	ErrCorruptArchive = errors.New("archive: corrupt archive")
	// ErrArchiveTooLarge reports an archive file larger than MaxArchiveBytes.
	ErrArchiveTooLarge = errors.New("archive: archive exceeds byte limit")
	// ErrEntryLimitExceeded reports more archive entries than MaxEntries.
	ErrEntryLimitExceeded = errors.New("archive: entry limit exceeded")
	// ErrPageTooLarge reports a regular entry larger than MaxPageBytes after decoding.
	ErrPageTooLarge = errors.New("archive: page exceeds byte limit")
	// ErrTotalBytesExceeded reports decoded regular-entry bytes beyond MaxTotalBytes.
	ErrTotalBytesExceeded = errors.New("archive: total byte limit exceeded")
	// ErrUnsafeEntry reports a symlink, hard link, junction, or other redirection.
	ErrUnsafeEntry = errors.New("archive: unsafe entry")
	// ErrEncryptedArchive reports archive or file encryption, which is unsupported.
	ErrEncryptedArchive = errors.New("archive: encrypted archive")
	// ErrMultiVolumeArchive reports a RAR archive that continues in another volume.
	ErrMultiVolumeArchive = errors.New("archive: multi-volume archive")
	// ErrDictionaryTooLarge reports a RAR dictionary larger than MaxDictionaryBytes.
	ErrDictionaryTooLarge = errors.New("archive: dictionary exceeds byte limit")
	// ErrInvalidImage reports an image-looking entry that does not decode.
	ErrInvalidImage = errors.New("archive: invalid image")
	// ErrImageTooLarge reports raster dimensions exceeding MaxImagePixels.
	ErrImageTooLarge = errors.New("archive: image exceeds pixel limit")
	// ErrUnsupportedImageType reports an image type this package cannot decode.
	ErrUnsupportedImageType = errors.New("archive: unsupported image type")
	// ErrOutputCollision reports an existing generated output filename.
	ErrOutputCollision = errors.New("archive: output filename already exists")
)

type archiveKind uint8

const (
	archiveZIP archiveKind = iota + 1
	archiveRAR
)

type extractionState struct {
	created []string
}

func (s *extractionState) track(path string) {
	s.created = append(s.created, path)
}

func (s *extractionState) cleanup() {
	for i := len(s.created) - 1; i >= 0; i-- {
		_ = os.Remove(s.created[i])
	}
}

type pageCandidate struct {
	name      string
	tempPath  string
	size      int64
	mediaType string
}

// Extract validates and extracts image entries from a ZIP or RAR4/RAR5
// archive. Entries are decoded in archive order, which is required for solid
// RAR archives, and are written in natural filename order after validation.
func Extract(ctx context.Context, inputPath, outputDir string, limits Limits) (pages []Page, err error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err = checkContext(ctx); err != nil {
		return nil, err
	}
	limits, err = normalizeLimits(limits)
	if err != nil {
		return nil, err
	}
	if err = validateInput(inputPath, limits); err != nil {
		return nil, err
	}
	if err = prepareOutputDir(outputDir); err != nil {
		return nil, err
	}

	kind, err := detectArchiveKind(ctx, inputPath)
	if err != nil {
		return nil, err
	}

	state := new(extractionState)
	defer func() {
		if err != nil {
			state.cleanup()
		}
	}()

	var candidates []*pageCandidate
	switch kind {
	case archiveZIP:
		candidates, err = extractZIP(ctx, inputPath, outputDir, limits, state)
	case archiveRAR:
		candidates, err = extractRAR(ctx, inputPath, outputDir, limits, state)
	default:
		err = fmt.Errorf("%w: unknown format", ErrUnsupportedArchive)
	}
	if err != nil {
		return nil, err
	}
	if err = checkContext(ctx); err != nil {
		return nil, err
	}
	return materializePages(ctx, outputDir, candidates, state)
}

func normalizeLimits(l Limits) (Limits, error) {
	d := DefaultLimits
	if l.MaxEntries == 0 {
		l.MaxEntries = d.MaxEntries
	}
	if l.MaxPageBytes == 0 {
		l.MaxPageBytes = d.MaxPageBytes
	}
	if l.MaxTotalBytes == 0 {
		l.MaxTotalBytes = d.MaxTotalBytes
	}
	if l.MaxArchiveBytes == 0 {
		l.MaxArchiveBytes = d.MaxArchiveBytes
	}
	if l.MaxDictionaryBytes == 0 {
		l.MaxDictionaryBytes = d.MaxDictionaryBytes
	}
	if l.MaxEntries < 1 || l.MaxPageBytes < 1 || l.MaxTotalBytes < 1 || l.MaxArchiveBytes < 1 || l.MaxDictionaryBytes < 1 {
		return Limits{}, ErrInvalidLimits
	}
	if l.MaxDictionaryBytes > maxRARDictionaryBytes {
		return Limits{}, fmt.Errorf("%w: dictionary exceeds rardecode maximum", ErrInvalidLimits)
	}
	return l, nil
}

func validateInput(inputPath string, limits Limits) error {
	if inputPath == "" {
		return fmt.Errorf("%w: empty path", ErrInvalidInput)
	}
	info, err := os.Lstat(inputPath)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return fmt.Errorf("%w: archive must be a regular file", ErrInvalidInput)
	}
	if info.Size() > limits.MaxArchiveBytes {
		return fmt.Errorf("%w: %d > %d", ErrArchiveTooLarge, info.Size(), limits.MaxArchiveBytes)
	}
	return nil
}

func prepareOutputDir(outputDir string) error {
	if outputDir == "" {
		return fmt.Errorf("%w: empty path", ErrInvalidOutput)
	}
	if err := os.MkdirAll(outputDir, 0700); err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidOutput, err)
	}
	info, err := os.Lstat(outputDir)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidOutput, err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return fmt.Errorf("%w: output must be a directory", ErrInvalidOutput)
	}
	return nil
}

func detectArchiveKind(ctx context.Context, inputPath string) (archiveKind, error) {
	f, err := os.Open(inputPath)
	if err != nil {
		return 0, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	cf := &contextFile{ctx: ctx, file: f}
	defer cf.Close()

	var header [8]byte
	n, readErr := io.ReadFull(cf, header[:])
	if readErr != nil && !errors.Is(readErr, io.EOF) && !errors.Is(readErr, io.ErrUnexpectedEOF) {
		return 0, readErr
	}
	if n >= 4 && bytes.Equal(header[:4], []byte("PK\x03\x04")) {
		return archiveZIP, nil
	}
	if n >= 4 && bytes.Equal(header[:4], []byte("PK\x05\x06")) {
		return archiveZIP, nil
	}
	if n >= 6 && bytes.Equal(header[:6], []byte("Rar!\x1a\x07")) {
		return archiveRAR, nil
	}
	return 0, fmt.Errorf("%w: unknown signature", ErrUnsupportedArchive)
}

func extractZIP(ctx context.Context, inputPath, outputDir string, limits Limits, state *extractionState) ([]*pageCandidate, error) {
	f, err := os.Open(inputPath)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	cf := &contextFile{ctx: ctx, file: f}
	defer cf.Close()

	info, err := cf.Stat()
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	if info.Size() > limits.MaxArchiveBytes {
		return nil, fmt.Errorf("%w: %d > %d", ErrArchiveTooLarge, info.Size(), limits.MaxArchiveBytes)
	}
	// Restrict all random reads to the input's observed size, including the
	// preflight that caps directory entries before zip.NewReader allocates them.
	input := io.NewSectionReader(cf, 0, info.Size())
	if err := preflightZIP(input, info.Size(), limits.MaxEntries); err != nil {
		return nil, normalizeArchiveError(err)
	}
	zr, err := zip.NewReader(input, info.Size())
	if err != nil {
		return nil, normalizeArchiveError(err)
	}

	totalRemaining := limits.MaxTotalBytes
	capacity := min(len(zr.File), limits.MaxEntries)
	candidates := make([]*pageCandidate, 0, capacity)
	for index, file := range zr.File {
		if err := checkContext(ctx); err != nil {
			return nil, err
		}
		if index+1 > limits.MaxEntries {
			return nil, fmt.Errorf("%w: %d > %d", ErrEntryLimitExceeded, index+1, limits.MaxEntries)
		}
		if file.Flags&0x1 != 0 {
			return nil, fmt.Errorf("%w: %s", ErrEncryptedArchive, file.Name)
		}
		mode := file.Mode()
		if mode&fs.ModeSymlink != 0 || mode.Type()&^fs.ModeDir != 0 {
			return nil, fmt.Errorf("%w: %s", ErrUnsafeEntry, file.Name)
		}
		if mode.IsDir() || strings.HasSuffix(file.Name, "/") {
			continue
		}

		entry, err := file.Open()
		if err != nil {
			return nil, normalizeArchiveError(err)
		}
		candidate, processErr := consumeEntry(ctx, file.Name, entry, outputDir, limits.MaxPageBytes, &totalRemaining, state)
		closeErr := entry.Close()
		if processErr != nil {
			return nil, normalizeArchiveError(processErr)
		}
		if closeErr != nil {
			return nil, normalizeArchiveError(closeErr)
		}
		if candidate != nil {
			candidates = append(candidates, candidate)
		}
	}
	return candidates, nil
}

func extractRAR(ctx context.Context, inputPath, outputDir string, limits Limits, state *extractionState) ([]*pageCandidate, error) {
	f, err := os.Open(inputPath)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	cf := &contextFile{ctx: ctx, file: f}
	defer cf.Close()

	info, err := cf.Stat()
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidInput, err)
	}
	if info.Size() > limits.MaxArchiveBytes {
		return nil, fmt.Errorf("%w: %d > %d", ErrArchiveTooLarge, info.Size(), limits.MaxArchiveBytes)
	}
	archiveReader := &archiveLimitReader{ctx: ctx, reader: cf, remaining: limits.MaxArchiveBytes}
	// This bounds rardecode's reported RAR window. In v2.4.1, RAR4 PPMd also
	// takes its model memory (maxMB) from the compressed stream; the dependency
	// exposes no public option to cap that separate allocation.
	rdr, err := rardecode.NewReader(archiveReader,
		rardecode.MaxDictionarySize(limits.MaxDictionaryBytes),
	)
	if err != nil {
		return nil, normalizeArchiveError(err)
	}

	totalRemaining := limits.MaxTotalBytes
	candidates := make([]*pageCandidate, 0)
	for index := 0; ; index++ {
		if err := checkContext(ctx); err != nil {
			return nil, err
		}
		header, nextErr := rdr.Next()
		if errors.Is(nextErr, io.EOF) {
			break
		}
		if nextErr != nil {
			return nil, normalizeArchiveError(nextErr)
		}
		if index+1 > limits.MaxEntries {
			return nil, fmt.Errorf("%w: %d > %d", ErrEntryLimitExceeded, index+1, limits.MaxEntries)
		}
		if header.Encrypted || header.HeaderEncrypted {
			return nil, fmt.Errorf("%w: %s", ErrEncryptedArchive, header.Name)
		}
		if header.LinkType != rardecode.LinkTypeNone || header.Mode()&fs.ModeSymlink != 0 {
			return nil, fmt.Errorf("%w: %s", ErrUnsafeEntry, header.Name)
		}
		if header.IsDir {
			continue
		}

		candidate, processErr := consumeEntry(ctx, header.Name, rdr, outputDir, limits.MaxPageBytes, &totalRemaining, state)
		if processErr != nil {
			return nil, normalizeArchiveError(processErr)
		}
		if candidate != nil {
			candidates = append(candidates, candidate)
		}
	}
	return candidates, nil
}

func consumeEntry(ctx context.Context, name string, reader io.Reader, outputDir string, maxPageBytes int64, totalRemaining *int64, state *extractionState) (*pageCandidate, error) {
	if err := checkContext(ctx); err != nil {
		return nil, err
	}
	temp, err := os.CreateTemp(outputDir, ".comic-entry-*")
	if err != nil {
		return nil, fmt.Errorf("%w: create temporary file: %v", ErrInvalidOutput, err)
	}
	tempPath := temp.Name()
	state.track(tempPath)
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tempPath)
		}
	}()

	limited := &entryLimitReader{
		ctx:            ctx,
		reader:         reader,
		pageRemaining:  maxPageBytes,
		totalRemaining: totalRemaining,
	}
	buffer := make([]byte, 1<<20)
	var size int64
	for {
		if err := checkContext(ctx); err != nil {
			_ = temp.Close()
			return nil, err
		}
		n, readErr := limited.Read(buffer)
		if n > 0 {
			if err := checkContext(ctx); err != nil {
				_ = temp.Close()
				return nil, err
			}
			written, writeErr := temp.Write(buffer[:n])
			if writeErr != nil {
				_ = temp.Close()
				return nil, writeErr
			}
			if written != n {
				_ = temp.Close()
				return nil, io.ErrShortWrite
			}
			size += int64(n)
		}
		if readErr != nil {
			if closeErr := temp.Close(); closeErr != nil && errors.Is(readErr, io.EOF) {
				return nil, closeErr
			}
			if !errors.Is(readErr, io.EOF) {
				return nil, readErr
			}
			break
		}
	}

	mediaType, ok, err := inspectImage(ctx, tempPath, name)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, nil
	}
	removeTemp = false
	return &pageCandidate{name: name, tempPath: tempPath, size: size, mediaType: mediaType}, nil
}

func inspectImage(ctx context.Context, path, name string) (mediaType string, ok bool, err error) {
	if err = checkContext(ctx); err != nil {
		return "", false, err
	}
	f, err := os.Open(path)
	if err != nil {
		return "", false, err
	}
	defer f.Close()

	header := make([]byte, 512)
	n, readErr := f.Read(header)
	if readErr != nil && !errors.Is(readErr, io.EOF) {
		return "", false, readErr
	}
	contentType := http.DetectContentType(header[:n])
	imageCandidate := imageName(name) || strings.HasPrefix(contentType, "image/")
	// x/image v0.46.0 does not decode animation. Reject the VP8X animation
	// flag explicitly, including files with an otherwise decodable still frame.
	if n > 20 && string(header[:4]) == "RIFF" && string(header[8:16]) == "WEBPVP8X" && header[20]&2 != 0 {
		return "", false, fmt.Errorf("%w: animated WebP: %s", ErrUnsupportedImageType, name)
	}
	if _, err = f.Seek(0, io.SeekStart); err != nil {
		return "", false, err
	}
	reader := &contextFile{ctx: ctx, file: f}
	// The pinned x/image v0.46.0 returns WebP VP8X configuration before
	// decoding ALPH, and validates VP8/VP8L dimensions against VP8X before
	// allocating the full raster. Keep both properties when upgrading it.
	config, format, decodeErr := image.DecodeConfig(reader)
	if decodeErr != nil {
		if err = checkContext(ctx); err != nil {
			return "", false, err
		}
		if !imageCandidate && (errors.Is(decodeErr, image.ErrFormat) || errors.Is(decodeErr, io.EOF)) {
			return "", false, nil
		}
		return "", false, fmt.Errorf("%w: %s: %v", ErrInvalidImage, name, decodeErr)
	}
	mediaType, ok = imageMediaType(format)
	if !ok {
		return "", false, fmt.Errorf("%w: %s (%s)", ErrUnsupportedImageType, name, format)
	}
	if err = checkImageDimensions(config.Width, config.Height); err != nil {
		return "", false, fmt.Errorf("%w: %s", err, name)
	}
	if _, err = reader.Seek(0, io.SeekStart); err != nil {
		return "", false, err
	}
	_, _, decodeErr = image.Decode(reader)
	if err = checkContext(ctx); err != nil {
		return "", false, err
	}
	if decodeErr != nil {
		return "", false, fmt.Errorf("%w: %s: %v", ErrInvalidImage, name, decodeErr)
	}
	return mediaType, true, nil
}

func checkImageDimensions(width, height int) error {
	if width <= 0 || height <= 0 {
		return fmt.Errorf("%w: invalid dimensions", ErrInvalidImage)
	}
	// Divide first so a malicious width*height cannot overflow an int.
	if width > MaxImagePixels/height {
		return ErrImageTooLarge
	}
	return nil
}

func imageName(name string) bool {
	switch strings.ToLower(filepath.Ext(name)) {
	case ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".tif", ".tiff", ".avif", ".jxl", ".heic", ".heif", ".svg":
		return true
	default:
		return false
	}
}

func imageMediaType(format string) (string, bool) {
	switch strings.ToLower(format) {
	case "png":
		return "image/png", true
	case "jpeg":
		return "image/jpeg", true
	case "gif":
		return "image/gif", true
	case "webp":
		return "image/webp", true
	default:
		return "", false
	}
}

func materializePages(ctx context.Context, outputDir string, candidates []*pageCandidate, state *extractionState) ([]Page, error) {
	sort.SliceStable(candidates, func(i, j int) bool {
		return naturalCompare(candidates[i].name, candidates[j].name) < 0
	})
	pages := make([]Page, 0, len(candidates))
	for index, candidate := range candidates {
		if err := checkContext(ctx); err != nil {
			return nil, err
		}
		fileName := fmt.Sprintf("page-%06d", index+1)
		filePath := filepath.Join(outputDir, fileName)
		if _, err := os.Lstat(filePath); err == nil {
			return nil, fmt.Errorf("%w: %s", ErrOutputCollision, fileName)
		} else if !errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("%w: %v", ErrInvalidOutput, err)
		}
		if err := os.Rename(candidate.tempPath, filePath); err != nil {
			return nil, fmt.Errorf("%w: rename page: %v", ErrInvalidOutput, err)
		}
		state.track(filePath)
		pages = append(pages, Page{
			Name:      candidate.name,
			File:      filePath,
			Size:      candidate.size,
			MediaType: candidate.mediaType,
		})
	}
	return pages, nil
}

func naturalCompare(a, b string) int {
	aa, bb := strings.ToLower(a), strings.ToLower(b)
	for i, j := 0, 0; i < len(aa) && j < len(bb); {
		adigit, bdigit := isASCIIDigit(aa[i]), isASCIIDigit(bb[j])
		if adigit && bdigit {
			ai, bj := i, j
			for i < len(aa) && isASCIIDigit(aa[i]) {
				i++
			}
			for j < len(bb) && isASCIIDigit(bb[j]) {
				j++
			}
			an, bn := strings.TrimLeft(aa[ai:i], "0"), strings.TrimLeft(bb[bj:j], "0")
			if len(an) != len(bn) {
				if len(an) < len(bn) {
					return -1
				}
				return 1
			}
			if c := strings.Compare(an, bn); c != 0 {
				return c
			}
			if i-ai != j-bj {
				if i-ai < j-bj {
					return -1
				}
				return 1
			}
			continue
		}
		if aa[i] != bb[j] {
			if aa[i] < bb[j] {
				return -1
			}
			return 1
		}
		i++
		j++
	}
	if len(aa) != len(bb) {
		if len(aa) < len(bb) {
			return -1
		}
		return 1
	}
	return strings.Compare(a, b)
}

func isASCIIDigit(c byte) bool {
	return c >= '0' && c <= '9'
}

func normalizeArchiveError(err error) error {
	if err == nil {
		return nil
	}
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded),
		errors.Is(err, ErrInvalidInput), errors.Is(err, ErrInvalidOutput),
		errors.Is(err, ErrArchiveTooLarge), errors.Is(err, ErrEntryLimitExceeded),
		errors.Is(err, ErrPageTooLarge), errors.Is(err, ErrTotalBytesExceeded),
		errors.Is(err, ErrUnsafeEntry), errors.Is(err, ErrEncryptedArchive),
		errors.Is(err, ErrMultiVolumeArchive), errors.Is(err, ErrDictionaryTooLarge),
		errors.Is(err, ErrInvalidImage), errors.Is(err, ErrImageTooLarge),
		errors.Is(err, ErrUnsupportedArchive), errors.Is(err, ErrUnsupportedImageType):
		return err
	case errors.Is(err, rardecode.ErrArchiveEncrypted), errors.Is(err, rardecode.ErrArchivedFileEncrypted):
		return fmt.Errorf("%w: %v", ErrEncryptedArchive, err)
	case errors.Is(err, rardecode.ErrMultiVolume):
		return fmt.Errorf("%w: %v", ErrMultiVolumeArchive, err)
	case errors.Is(err, rardecode.ErrDictionaryTooLarge):
		return fmt.Errorf("%w: %v", ErrDictionaryTooLarge, err)
	default:
		return fmt.Errorf("%w: %v", ErrCorruptArchive, err)
	}
}

func checkContext(ctx context.Context) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
		return nil
	}
}

type contextFile struct {
	ctx  context.Context
	file *os.File
}

func (f *contextFile) Read(p []byte) (int, error) {
	if err := checkContext(f.ctx); err != nil {
		return 0, err
	}
	return f.file.Read(p)
}

func (f *contextFile) ReadAt(p []byte, offset int64) (int, error) {
	if err := checkContext(f.ctx); err != nil {
		return 0, err
	}
	return f.file.ReadAt(p, offset)
}

func (f *contextFile) Seek(offset int64, whence int) (int64, error) {
	if err := checkContext(f.ctx); err != nil {
		return 0, err
	}
	return f.file.Seek(offset, whence)
}

func (f *contextFile) Stat() (os.FileInfo, error) {
	if err := checkContext(f.ctx); err != nil {
		return nil, err
	}
	return f.file.Stat()
}

func (f *contextFile) Close() error {
	return f.file.Close()
}

type contextReaderAt struct {
	ctx    context.Context
	reader io.ReaderAt
}

func (r contextReaderAt) ReadAt(p []byte, offset int64) (int, error) {
	if err := checkContext(r.ctx); err != nil {
		return 0, err
	}
	return r.reader.ReadAt(p, offset)
}

type archiveLimitReader struct {
	ctx       context.Context
	reader    io.Reader
	remaining int64
}

func (r *archiveLimitReader) Read(p []byte) (int, error) {
	if err := checkContext(r.ctx); err != nil {
		return 0, err
	}
	if len(p) == 0 {
		return 0, nil
	}
	if r.remaining == 0 {
		var probe [1]byte
		n, err := r.reader.Read(probe[:])
		if n > 0 || err == nil {
			return 0, ErrArchiveTooLarge
		}
		return 0, err
	}
	if int64(len(p)) > r.remaining {
		p = p[:r.remaining]
	}
	n, err := r.reader.Read(p)
	r.remaining -= int64(n)
	return n, err
}

type entryLimitReader struct {
	ctx            context.Context
	reader         io.Reader
	pageRemaining  int64
	totalRemaining *int64
}

func (r *entryLimitReader) Read(p []byte) (int, error) {
	if err := checkContext(r.ctx); err != nil {
		return 0, err
	}
	if len(p) == 0 {
		return 0, nil
	}
	limit := int64(len(p))
	if r.pageRemaining < limit {
		limit = r.pageRemaining
	}
	if *r.totalRemaining < limit {
		limit = *r.totalRemaining
	}
	if limit == 0 {
		var probe [1]byte
		n, err := r.reader.Read(probe[:])
		if n > 0 || err == nil {
			if r.pageRemaining == 0 {
				return 0, ErrPageTooLarge
			}
			return 0, ErrTotalBytesExceeded
		}
		return 0, err
	}
	n, err := r.reader.Read(p[:limit])
	r.pageRemaining -= int64(n)
	*r.totalRemaining -= int64(n)
	return n, err
}
